# Generated by Django 3.1.2 on 2020-10-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=128)),
                ('las_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
        ),
    ]
