# Generated by Django 3.1.2 on 2020-10-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chrsikimb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
