# Generated by Django 3.1.2 on 2020-10-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chrsikimb_app', '0002_auto_20201019_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
